### ISSUE TITLE
Can't change to another screen after Done clicked

### ISSUE THREAD

**Issue by ebenj** [kajensen/Onboarding#1]
Hi,

On onboardingViewControllerDoneTapped() I try the following code but nothing happens. How culd I dismiss the onboarding and move to the log in screen?

self.navigationController?.pushViewController(self.storyboard?.instantiateViewController(withIdentifier: "loginView") as! LogInViewController, animated: true)

**Comment by kajensen** [comment]
You have to implement the delegate method onboardingViewControllerDoneTapped, where you will dismiss the onboardingVC and show whatever's next.

**Comment by ebenj** [comment]
Hi,

I implemented the method and included the code that I mentioned inside that
method. But nothing happens. See code below based in your example:

extension myOnboardingViewController: OnboardingViewControllerDelegate {

func onboardingViewControllerDoneTapped() {

self.navigationController?.pushViewController(self.storyboard?.
instantiateViewController(withIdentifier: "loginView") as!
LogInViewController, animated: true)

}

}


Thanks

2017-04-19 9:40 GMT-04:00 Kurt <notifications@github.com>:

**Comment by kajensen** [comment]
add
`dissmissViewController(true, completion: nil)`
as the first line of onboardingViewControllerDoneTapped
